name: tests

on:
  push:
    tags:
      - v*
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - uses: actions/checkout@v4
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7

      - name: go tests
        run: go test -v -cover ./...

      - name: go tests - race
        run: go test -race -v -cover ./...

      - name: go tests - coverprofile
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.txt
